### ISSUE TITLE
NameError: global name 'rtltcp' is not defined

### ISSUE THREAD

**Issue by Nold360** [EarToEarOak/RTLSDR-Scanner#31]
Hi,

I got this error when trying to start a scan using a rtl_tcp device:

Exception in thread Scan:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/nold/.local/lib/python2.7/site-packages/rtlsdr_scanner/scan.py", line 104, in run
    tuner = self.__rtl_setup()
  File "/home/nold/.local/lib/python2.7/site-packages/rtlsdr_scanner/scan.py", line 92, in __rtl_setup
    self.sdr = rtltcp.RtlTcp(self.server, self.port, self.notify)
NameError: global name 'rtltcp' is not defined

Adding the line "include rtltcp" to scan.py fixed it for me.

**Comment by EarToEarOak** [comment]
Hi,

Thanks for the information, I've already committed a fix but haven't pushed it yet.

I should have a release ready in the next few hours.
