### ISSUE TITLE
Installation on Mac OS Catalina

### ISSUE THREAD

**Issue by promo776** [EarToEarOak/RTLSDR-Scanner#63]
getting this error when attempting to run:

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 153, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Library/Python/3.7/site-packages/rtlsdr_scanner/__main__.py", line 39
    print 'Import error: {}'.format(error)

SyntaxError: invalid syntax

**Comment by keptenkurk** [comment]
The master branch here is not suited for Python 3.7. Neither is it suited for the later versions of wxPython and other dependencies. The most advanced fork of this project is to be found at https://github.com/CdeMills/RTLSDR-Scanner.
Currently trying to get it running using:
OS: Windows-10-10.0.17134-SP0, AMD64
Python: 3.6.8
matplotlib: 3.2.1
NumPy: 1.17.3
Pillow: 7.1.2
pySerial: 3.4
visvis: 1.12.4
wxPython: 4.1.0 msw (phoenix) wxWidgets 3.1.4
apart from some hurdles basic functions work.
