### ISSUE TITLE
Scan save does not work 

### ISSUE THREAD

**Issue by kaklik** [EarToEarOak/RTLSDR-Scanner#67]
In case of use `File -> Save as` option. The Scanner utility declares the "Status: Saving..."

![image](https://user-images.githubusercontent.com/1194177/114687798-64253980-9d14-11eb-8c1d-14dee9022af1.png)

But, the produced file has zero size

    $ ls -la | grep rfs
    -rw-rw-r--  1 kaklik kaklik        0 dub 10 13:04 Scan 150.0-500.0MHz_chotilsko.rfs
    -rw-rw-r--  1 kaklik kaklik        0 dub 10 12:53 Scan 150.0-500.0MHz_praha.rfs
    -rw-rw-r--  1 kaklik kaklik        0 dub 14 11:28 Scan500-1000.0MHz_chotilsko_noANT.rfs
    -rw-rw-r--  1 kaklik kaklik        0 dub 10 09:19 Scan80.0-120.0MHz_praha.rfs

Terminal output is: 

    Traceback (most recent call last):
      File "/home/kaklik/programy/RTLSDR-Scanner/rtlsdr_scanner/main_window.py", line 485, in __on_save
        save_plot(fullName, self.scanInfo, self.spectrum, self.locations)
      File "/home/kaklik/programy/RTLSDR-Scanner/rtlsdr_scanner/file.py", line 408, in save_plot
        handle.write(json.dumps(data, indent=4))
    TypeError: a bytes-like object is required, not 'str'

**Comment by petterreinholdtsen** [comment]
A fix for this is available in https://github.com/CdeMills/RTLSDR-Scanner/pull/2 .
