### ISSUE TITLE
pyrtlsdr dependency issue

### ISSUE THREAD

**Issue by jamesmcguirepro** [EarToEarOak/RTLSDR-Scanner#72]
If I install RTLSDR-Scanner on Windows, I get this error:
```
C:\Users\Owner>c:\Python27\python.exe -m rtlsdr_scanner
Traceback (most recent call last):
  File "c:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\Python27\lib\site-packages\rtlsdr_scanner\__main__.py", line 36, in <module>
    import rtlsdr  # @UnusedImport
  File "c:\Python27\lib\site-packages\rtlsdr\__init__.py", line 56, in <module>
    from .librtlsdr import librtlsdr
  File "c:\Python27\lib\site-packages\rtlsdr\librtlsdr.py", line 188, in <module>
    f = librtlsdr.rtlsdr_set_bias_tee
  File "c:\Python27\lib\ctypes\__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "c:\Python27\lib\ctypes\__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'rtlsdr_set_bias_tee' not found
```

Running the dependency check reveals this error:
```
c:\Python27\Lib\site-packages\rtlsdr_scanner>c:\Python27\python.exe rtlsdr_scan_diag.py
rtlsdr_scan_diag

Tests for missing libraries

Testing for wxPython
Testing for Numpy
Testing for matplotlib
Testing for pySerial
Testing for pyrtlsdr
pyrtlsdr not found
        Download from 'https://github.com/roger-/pyrtlsdr'

Testing for Pillow

Problems found, please install the libraries for Python 2.7
Further instructions can be found at http://eartoearoak.com/software/rtlsdr-scanner/rtlsdr-scanner-installation

Press [Return]
```

**Comment by jamesmcguirepro** [comment]
Manually installing pyrtlsdr v0.2.92 seems to solve the issue:
```
c:\Python27\python.exe -m pip install pyrtlsdr==0.2.91
```

I took at stab at locking down the dependency version the installer fetches: https://github.com/EarToEarOak/RTLSDR-Scanner/compare/master...jamesmcguirepro:RTLSDR-Scanner:patch-1.  Happy to open a PR if wanted.
